sudo: required
services:
- docker

language: node_js
node_js:
  - "6"

before_install:
  - pip install --upgrade --user awscli
  - cd lambda

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then lambda/bin/lambda-deploy.sh; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then lambda/bin/docker-build-and-deploy.sh; fi
